# Generated by Django 5.2.13 on 2026-04-27 04:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店名')),
                ('location', models.CharField(max_length=200, verbose_name='場所')),
                ('lunch_end_time', models.TimeField(help_text='ランチ提供終了時刻（例：13:30）', verbose_name='ランチ提供終了時刻')),
                ('estimated_time_minutes', models.PositiveIntegerField(help_text='往復・提供・食事を含めた平均所要時間（分）', verbose_name='平均所要時間（分）')),
                ('is_approved', models.BooleanField(default=False, verbose_name='承認済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lunch_places', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
            ],
            options={
                'verbose_name': '昼食先',
                'verbose_name_plural': '昼食先',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評価')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('lunch_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lunch.lunchplace', verbose_name='昼食先')),
            ],
            options={
                'verbose_name': 'レビュー',
                'verbose_name_plural': 'レビュー',
                'ordering': ['-created_at'],
            },
        ),
    ]
